CreateThread(function()
    AddTextEntry('legacy8', "Charger 1") 
    AddTextEntry('legacy11', "Charger 2") 
    AddTextEntry('legacy12', "Crownvic") 
    AddTextEntry('legacy2', "Ford Explorer") 
    AddTextEntry('legacy1', "Ford Explorer 2") 
    AddTextEntry('legacy3', "Ford Raptor") 
    AddTextEntry('legacy4', "Tahoe") 
    AddTextEntry('legacy5', "Vartic dzip") 
    AddTextEntry('legacy6', "Policijski dzip") 
    AddTextEntry('legacy9', "Charger 3") 
    AddTextEntry('legacy16', "Offroad") 
    AddTextEntry('legacy17', "Mustang") 
    AddTextEntry('legacy18', "Cammaro") 
    AddTextEntry('legacy19', "Chellanger") 
    AddTextEntry('nkbisonum', "Policijski kamionet unmarked") 
    AddTextEntry('nkfugitiveum', "Cheval unmarked") 
    AddTextEntry('nkjester4um', "Presretač Mazda unmarked") 
    AddTextEntry('nkkomodaum', "Policiska Alfa unmarked") 
    AddTextEntry('nklandstalker2um', "Landstalker unmarked") 
    AddTextEntry('nkomnisegtum', "Elektricni Audi unmarked") 
    AddTextEntry('nkparagonum', "Presretač Jaguar unmarked") 
    AddTextEntry('nkrhinehartum', "Audi karavan unmarked") 
    AddTextEntry('nkstingerttum', "Presretač Ferrari unmarked") 
    AddTextEntry('nktailgatersum', "Audi A4 unmarked") 
    AddTextEntry('nktenfum', "Presretač Audi R8 unmarked") 
    AddTextEntry('nktorrenceum', "Patrolni Ford unmarked") 
    AddTextEntry('nkbison', "Policijski kamionet") 
    AddTextEntry('nkfugitive', "Cheval") 
    AddTextEntry('nkjester4', "Presretač Mazda") 
    AddTextEntry('nkkomoda', "Policiska Alfa") 
    AddTextEntry('nklandstalker2', "Landstalker") 
    AddTextEntry('nkomnisegt', "Elektricni Audi") 
    AddTextEntry('nkparagon', "Presretač Jaguar") 
    AddTextEntry('nkrhinehart', "Audi karavan") 
    AddTextEntry('nkstingertt', "Presretač Ferrari") 
    AddTextEntry('nktailgaters', "Audi A4") 
    AddTextEntry('nktenf', "Presretač Audi R8") 
    AddTextEntry('nktorrence', "Patrolni Ford") 
    AddTextEntry('nkbf400', 'Policijski motor')
    AddTextEntry('riot', 'Riot Blinda')
end)